version: "3.9"

services:
  ros2:
    container_name: ros2
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${XAUTHORITY}:/tmp/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/home/ros/src
    privileged: true
    tty: true
    # env_file:
    #   - .env
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
      - ROS_DOMAIN_ID=35
    devices:
      - /dev/tty*:/dev/tty*
    network_mode: host
    # command: bash -c "source /home/ros/install/setup.bash && ros2 launch dyno_jackal_bringup hardware.launch.py"
    command: tail -f /dev/null
    restart: always
